### ISSUE TITLE
in vue 3 composition api vue-focus-lock throws an error

### ISSUE THREAD

**Issue by shdow-monarch** [theKashey/vue-focus-lock#33]
```
Uncaught TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.render (index.js:1485:92)
    at renderComponentRoot (runtime-core.esm-bundler.js:914:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5649:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)
    at instance.update (runtime-core.esm-bundler.js:5763:56)
    at setupRenderEffect (runtime-core.esm-bundler.js:5777:9)
    at mountComponent (runtime-core.esm-bundler.js:5559:9)
    at processComponent (runtime-core.esm-bundler.js:5517:17)
    at patch (runtime-core.esm-bundler.js:5119:21)
    at mountChildren (runtime-core.esm-bundler.js:5303:13)
```

**`var _c=_vm._self._c||_h;` cannot read properties of undefined reading 'c'**

This above error was thrown while running vue-focus-lock in vue 3 composition api

**Comment by theKashey** [comment]
Hey mate. No solution yet, sorry.

**Comment by ltoussaint** [comment]
To give an update on this,
Difficult to find the exact problem but what I can say.

- The code works when I copy/paste the component in my Vue3 project.
- I had some issues with vue-demi trying to load `@vue/composition-api` even on my Vue3 project. It fixed the error after cleaning my deps and some caches

I think the problem comes from the build and the dependencies.
I tried some changes and tested different builds but I always encounters some errors
I even was thinking trying to build it using vite with only Vue3 support...

**Comment by theKashey** [comment]
Can be somehow related to post-install hooks powering vue-demi. Wondering if nuking node_modules (classic) can help.

**Comment by itsjustaaron** [comment]
+1, having the same issue and following along for updates. I also tried nuking node_modules - usually my go-to any time something doesn't work :) - and found no success, but was able to copy all the code into a new component as a temporary workaround.

**Comment by tbl0605** [comment]
Additionally to the `_vm._self is undefined` error I also have following error:
`[Vue warn]: Property "$createElement" was accessed during render but is not defined on instance.`

on line (from file vue-focus-lock/dist/index.js):
```
module.exports={render:function (){var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;
```

**Comment by theKashey** [comment]
Any help is more than welcomed

**Comment by nwoltman** [comment]
I think I figured it out. It's a problem with the pre-built file that's used when you import `vue-focus-lock`. It might be because this package is using `vue-template-compiler` to pre-build the file but that compiler is only for Vue 2.

To work around this issue for now, everything works fine if you import the Lock component directly:

```js
import FocusLock from 'vue-focus-lock/src/Lock.vue';
```

If you're using webpack with vue-loader and you're excluding node_modules, make sure to update the regex to *not* exclude vue-focus-lock:

```js
exclude: /node_modules[\\/](?!vue-focus-lock[\\/])/
```

**Comment by tbl0605** [comment]
Thank you very much @ltoussaint for your work!

@theKashey, I'm waiting for the (beta?) release then :)
Thank you again for this great library ;)

**Comment by theKashey** [comment]
3.0.0-beta.1 has been published. Will be promoted once somebody verifies the correctness of a new version.

**Comment by ltoussaint** [comment]
I have a problem with TypeScript support.
I will try to investigate later today

**Comment by theKashey** [comment]
Can I consider this as a _correctness verification_? 
@ltoussaint - please share details about the issue you were facing or I will release a new version in 24 hours...

**Comment by tbl0605** [comment]
> Can I consider this as a _correctness verification_?

If by  "correctness" you mean that everything works as expected for me, then I would say yes. 
But compared to @ltoussaint I haven't tried this version with typescript support (I use it in a complex project migrated from Vue 2 to Vue 3).

**Comment by ltoussaint** [comment]
I created a new PR to fix some typescript issues on specific context : https://github.com/theKashey/vue-focus-lock/pull/39
I struggled finding the real reason behind the typescript issue, but it's due to a specific tsconfig using `moduleResolution: 'bundler'`, which is used in nuxt3 project

@theKashey  After the PR is merged, we should be ready for a new major version ;-)

**Comment by theKashey** [comment]
In this case v3 goes live first thing in the morning

**Comment by theKashey** [comment]
v3.0.0 has been released 👍 
Kudos to @ltoussaint, it would not have happened without external contributions.
